ZeroWasteShop/ZeroWasteShop.Website/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ZeroWasteShop.Website.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ZeroWasteShop/ZeroWasteShop.Website/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZeroWasteShop.Website.Models;
using ZeroWasteShop.Website.ViewModels;

namespace ZeroWasteShop.Website.Properties.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult List(string category)
        {
            IEnumerable<Product> products;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                products = _productRepository.GetAllProducts.OrderBy(c => c.ProductId);
                currentCategory = "All Products";
            }
            else
            {
                products = _productRepository.GetAllProducts
                    .Where(c => c.Category.CategoryName == category);

                currentCategory = _categoryRepository.GetAllCategories
                    .FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new ProductListViewModel
            {
                Products = products,
                CurrentCategory = currentCategory
            });
        }

        public IActionResult Details(int id)
        {
            var product = _productRepository.GetProductById(id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }
    }
}

ZeroWasteShop/ZeroWasteShop.Website/Views/Shared/_Carousel.cshtml
<div class="d-none d-md-block" style="width: 100%">
    <div class="col-lg-12 col-md-12">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="~/images/carousel1.jpg" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/images/carousel2.jpg" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="~/images/carousel3.jpg" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" style="color: grey" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

ZeroWasteShop/ZeroWasteShop.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro"/>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/content/site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Zero Waste Shop</a> 
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a> 
                    </li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Contact" asp-action="Index">Contact <span class="sr-only">(current)</span></a> 
                    </li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
                <!-- Search form. Not implemented yet. -->
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
                <!-- End of search form. -->
            </div>
        </nav>
        <div class="row">
            @RenderBody()
        </div>
    </div>
</body>
</html>

ZeroWasteShop/ZeroWasteShop.Website/Views/Shared/_ProductCard.cshtml
@model Product

<div class="col-sm-6 col-md-4 col-lg-4">
    <div class="card">
        <img class="card-img-top" src="@Model.ImageThumbnailUrl" alt="product thumbnail image" />
        <div class="card-body">
            <h3 class="float-right">@Model.Price.ToString("c")</h3>
            <h5 class="card-title">@Model.Name</h5>
            <p class="card-text">@Model.Description</p>
            <a class="btn btn-primary" asp-controller="Product" asp-action="Details" asp-route-id="@Model.ProductId">Details</a>
            <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-productId="@Model.ProductId">Add to Cart</a>
        </div>
    </div>
</div>